FROM wangsijie/busybox
RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN code-server --install-extension ms-ceintl.vscode-language-pack-zh-hans
RUN code-server --install-extension ms-azuretools.vscode-docker
RUN code-server --install-extension dbaeumer.vscode-eslint
RUN code-server --install-extension eamodio.gitlens
RUN code-server --install-extension humao.rest-client
COPY code-argv.json /root/.local/share/code-server/User/argv.json
