name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: wangsijie
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: base image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: wangsijie/busybox:latest
      - name: coder-server image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.code
          push: true
          tags: wangsijie/code-server:latest
